### ISSUE TITLE
.ari output in Arpeggio web interface

### ISSUE THREAD

**Issue by washington-rosetta** [harryjubb/arpeggio#10]
Hello Harry and team, great work on creating arpeggio. I am currently using the web interface but I could not find the **_.ari_** output in the "full data package" output. Am I missing something?

**Comment by harryjubb** [comment]
Hi @washington-rosetta, thank you. You're right, it doesn't look like that file is included in the output.

Unfortunately I don't have access to the web service any more to investigate further, I'm not in a position to fully support it.

I'd recommend using the Python program, as it's also had a few updates since the publication of the web interface. The easiest way to get it running is to use the Dockerised version [as described in the readme](https://github.com/harryjubb/arpeggio#getting-started). There's also relevant information in the [FAQ](https://github.com/harryjubb/arpeggio#frequently-asked-questions). I hope those are helpful, apologies that that doesn't directly resolve your issue.

**Comment by washington-rosetta** [comment]
Thanks, @harryjubb. I am using the Docker version of your Python program now. It works great.
